# Generated by Django 5.2.6 on 2025-09-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('services', '0002_historicalservice_price_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employees', to='services.service'),
        ),
    ]
