# Generated by Django 5.2.6 on 2025-10-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_historicalemployeeweeklyschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lunch_start_time', models.TimeField()),
                ('lunch_end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
