# Generated by Django 5.2.6 on 2025-09-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory_historicalservice_active_and_more'),
        ('services', '0003_service_locations'),
    ]

    operations = [
    ]
