# Generated by Django 5.2.6 on 2025-09-12 21:31

from django.db import migrations


def copy_base_price_to_price(apps, schema_editor):
    """Copy data from base_price to price field"""
    Service = apps.get_model('services', 'Service')
    for service in Service.objects.all():
        if hasattr(service, 'base_price') and service.base_price is not None:
            service.price = service.base_price
            service.save(update_fields=['price'])


def reverse_copy_base_price_to_price(apps, schema_editor):
    """Reverse operation - copy price back to base_price"""
    Service = apps.get_model('services', 'Service')
    for service in Service.objects.all():
        if hasattr(service, 'base_price') and service.price is not None:
            service.base_price = service.price
            service.save(update_fields=['base_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_merge_20250913_0031'),
    ]

    operations = [
        migrations.RunPython(copy_base_price_to_price, reverse_copy_base_price_to_price),
    ]
