# Generated by Django 5.2.6 on 2025-09-12 21:32

from django.db import migrations


def remove_base_price_field(apps, schema_editor):
    """Remove the base_price field from the database"""
    # This is handled by the schema migration below
    pass


def reverse_remove_base_price_field(apps, schema_editor):
    """Reverse operation - not needed for this migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20250913_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='base_price',
        ),
    ]
