# Generated by Django 5.2.6 on 2025-09-12 22:08

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_remove_historicalguestaddress_guest_and_more'),
        ('reservations', '0002_historicalreservation_cancelled_at_and_more'),
        ('services', '0006_auto_20250913_0032'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_advance_booking_hours', models.PositiveIntegerField(default=24)),
                ('max_advance_booking_days', models.PositiveIntegerField(default=30)),
                ('cancellation_deadline_hours', models.PositiveIntegerField(default=24)),
                ('cancellation_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('no_show_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Every X days/weeks/months')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='Days of week for weekly pattern')),
                ('day_of_month', models.PositiveIntegerField(blank=True, help_text='Day of month for monthly pattern', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for recurring pattern', null=True)),
                ('max_occurrences', models.PositiveIntegerField(blank=True, help_text='Maximum number of occurrences', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of people'),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='parent_reservation',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Parent reservation for recurring appointments', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of people'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='parent_reservation',
            field=models.ForeignKey(blank=True, help_text='Parent reservation for recurring appointments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_reservations', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='reservationservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservationservice',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalRecurringPattern',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Every X days/weeks/months')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='Days of week for weekly pattern')),
                ('day_of_month', models.PositiveIntegerField(blank=True, help_text='Day of month for monthly pattern', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for recurring pattern', null=True)),
                ('max_occurrences', models.PositiveIntegerField(blank=True, help_text='Maximum number of occurrences', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical recurring pattern',
                'verbose_name_plural': 'historical recurring patterns',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='recurring_pattern',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.recurringpattern'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recurring_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.recurringpattern'),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('preferred_time_start', models.TimeField()),
                ('preferred_time_end', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='guests.guest')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='services.service')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('guest', 'service', 'preferred_date')},
            },
        ),
        migrations.DeleteModel(
            name='HistoricalReservationService',
        ),
    ]
