# Generated by Django 5.2.6 on 2025-09-15 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookingrule_recurringpattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.location'),
        ),
    ]
