# Generated by Django 5.2.6 on 2025-09-17 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employeecommission_employeetraining_and_more"),
        ("reservations", "0004_alter_reservation_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreservation",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="employees.employee",
            ),
        ),
    ]
