# Generated by Django 5.2.6 on 2025-09-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_housekeepingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_out_of_service',
            field=models.BooleanField(default=False, help_text='If true, room cannot be booked or used'),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='is_out_of_service',
            field=models.BooleanField(default=False, help_text='If true, room cannot be booked or used'),
        ),
    ]
