# Generated by Django 5.2.6 on 2025-09-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_add_is_out_of_service_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingtask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='housekeepingtask',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhousekeepingtask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalhousekeepingtask',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
