# Generated by Django 5.2.6 on 2025-09-28 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0011_alter_historical_housekeeping_created_at_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalhousekeepingtask",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalhousekeepingtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecurringpattern",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="recurringpattern",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
