# Generated by Django 5.2.6 on 2025-10-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_cancellationreason"),
        ("reservations", "0012_alter_historicalhousekeepingtask_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreservation",
            name="cancellation_reason",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="config.cancellationreason",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="cancellation_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="config.cancellationreason",
            ),
        ),
    ]
