# Generated by Django 5.2.6 on 2025-10-20 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0014_historicalreservation_is_first_for_guest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreservation",
            name="deposit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Required deposit amount",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="historicalreservation",
            name="deposit_paid",
            field=models.BooleanField(
                default=False, help_text="Whether deposit has been paid"
            ),
        ),
        migrations.AddField(
            model_name="historicalreservation",
            name="deposit_paid_at",
            field=models.DateTimeField(
                blank=True, help_text="When deposit was paid", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalreservation",
            name="deposit_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether a deposit is required for this reservation",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="deposit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Required deposit amount",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="deposit_paid",
            field=models.BooleanField(
                default=False, help_text="Whether deposit has been paid"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="deposit_paid_at",
            field=models.DateTimeField(
                blank=True, help_text="When deposit was paid", null=True
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="deposit_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether a deposit is required for this reservation",
            ),
        ),
    ]
