# Generated by Django 5.2.6 on 2025-10-13 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_historicalfinancialreport_historicalgiftcard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Unique key to prevent duplicate payment processing', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Unique key to prevent duplicate payment processing', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['idempotency_key'], name='pos_payment_idempot_98e77f_idx'),
        ),
    ]
