# Generated by Django 5.2.6 on 2025-10-13 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_guest_country_historicalguest_country'),
        ('pos', '0004_historicalinvoice_version_and_more'),
        ('reservations', '0014_historicalreservation_is_first_for_guest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'balance_due'], name='invoice_status_balance_idx'),
        ),
    ]
