# Generated by Django 5.2.6 on 2025-10-22 08:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0006_deposit_historicaldeposit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpayment",
            name="is_refunded",
        ),
        migrations.RemoveField(
            model_name="historicalpayment",
            name="refund_amount",
        ),
        migrations.RemoveField(
            model_name="historicalpayment",
            name="refund_date",
        ),
        migrations.RemoveField(
            model_name="historicalpayment",
            name="refund_reason",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_refunded",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="refund_amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="refund_date",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="refund_reason",
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Payment amount (must be positive)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("wallet", "Wallet"),
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("gift_card", "Gift Card"),
                    ("deposit", "Deposit"),
                    ("store_credit", "Store Credit"),
                ],
                help_text="Payment method",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular Payment"),
                    ("deposit_application", "Deposit Application"),
                    ("manual", "Manual Adjustment"),
                ],
                default="full",
                help_text="Type of payment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="completed",
                help_text="Payment status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Payment amount (must be positive)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("wallet", "Wallet"),
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("gift_card", "Gift Card"),
                    ("deposit", "Deposit"),
                    ("store_credit", "Store Credit"),
                ],
                help_text="Payment method",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular Payment"),
                    ("deposit_application", "Deposit Application"),
                    ("manual", "Manual Adjustment"),
                ],
                default="full",
                help_text="Type of payment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="completed",
                help_text="Payment status",
                max_length=20,
            ),
        ),
    ]
