# Generated by Django 5.2.6 on 2025-10-22 09:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0010_guest_country_historicalguest_country"),
        ("pos", "0010_default_historicaldeposit_updated_at"),
        ("reservations", "0015_add_deposit_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deposit",
            options={"ordering": ["-collected_at"]},
        ),
        migrations.AlterModelOptions(
            name="historicaldeposit",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical deposit",
                "verbose_name_plural": "historical deposits",
            },
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="historicaldeposit",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="historicalrefund",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="refund",
            name="payment",
        ),
        migrations.AddField(
            model_name="deposit",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Date after which deposit expires if not used",
                null=True,
            ),
        ),
        # updated_at field will be handled by 0013_fix_deposit_updated_at migration
        migrations.AddField(
            model_name="historicaldeposit",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Date after which deposit expires if not used",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalrefund",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalrefund",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalrefund",
            name="original_payment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The payment being refunded (if partial refund)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pos.payment",
            ),
        ),
        migrations.AddField(
            model_name="historicalrefund",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalrefund",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalrefund",
            name="refund_method",
            field=models.CharField(
                choices=[
                    ("original_payment", "Original Payment Method"),
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("store_credit", "Store Credit"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalrefund",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="refund",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refund",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="refund",
            name="original_payment",
            field=models.ForeignKey(
                blank=True,
                help_text="The payment being refunded (if partial refund)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="pos.payment",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refund_processing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="refund",
            name="refund_method",
            field=models.CharField(
                choices=[
                    ("original_payment", "Original Payment Method"),
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("store_credit", "Store Credit"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refund",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="collected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Collection"),
                    ("collected", "Collected (Not Applied)"),
                    ("partially_applied", "Partially Applied"),
                    ("fully_applied", "Fully Applied"),
                    ("refunded", "Refunded"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeposit",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeposit",
            name="collected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldeposit",
            name="created_at",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicaldeposit",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Collection"),
                    ("collected", "Collected (Not Applied)"),
                    ("partially_applied", "Partially Applied"),
                    ("fully_applied", "Fully Applied"),
                    ("refunded", "Refunded"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeposit",
            name="updated_at",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular Payment"),
                    ("deposit_application", "Deposit Application"),
                    ("manual", "Manual Adjustment"),
                ],
                default="regular",
                help_text="Type of payment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpaymentmethod",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="historicalrefund",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Refund amount (MUST be positive)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="historicalrefund",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("processed", "Processed/Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular Payment"),
                    ("deposit_application", "Deposit Application"),
                    ("manual", "Manual Adjustment"),
                ],
                default="regular",
                help_text="Type of payment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="refund",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Refund amount (MUST be positive)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refund_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("processed", "Processed/Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(
                fields=["guest", "-collected_at"], name="pos_deposit_guest_i_797237_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(fields=["status"], name="pos_deposit_status_988fd9_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["invoice", "-created_at"], name="pos_refund_invoice_8369c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["status"], name="pos_refund_status_ddc60c_idx"),
        ),
    ]
