# Generated by Django 5.2.6 on 2025-10-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0011_alter_deposit_options_and_more"),
    ]

    operations = []
