# Generated by Django 5.2.6 on 2025-10-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0012_merge_20251022_1301"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
