# Generated by Django 5.2.6 on 2025-10-22 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0013_deposit_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaldeposit",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
