# Generated by Django 5.2.6 on 2025-10-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0015_ensure_deposit_expiry_date_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaldeposit",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Date after which deposit expires if not used",
                null=True,
            ),
        ),
    ]
