# Generated by Django 5.2.6 on 2025-10-23 10:55

from django.db import migrations, models
from pos.migration_utils import safe_add_field_to_model, safe_drop_field_from_model


def ensure_historicaldeposit_expiry_date_field(apps, schema_editor):
    """Ensure expiry_date field exists on HistoricalDeposit table"""
    safe_add_field_to_model(apps, schema_editor, 'pos', 'historicaldeposit', 'expiry_date', 'date NULL')


def reverse_ensure_historicaldeposit_expiry_date_field(apps, schema_editor):
    """Remove expiry_date field if it exists"""
    safe_drop_field_from_model(apps, schema_editor, 'pos', 'historicaldeposit', 'expiry_date')


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_ensure_deposit_expiry_date_column'),
    ]

    operations = [
        migrations.RunPython(
            ensure_historicaldeposit_expiry_date_field,
            reverse_ensure_historicaldeposit_expiry_date_field
        ),
    ]
