# Generated by Django 5.2.6 on 2025-09-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='house_status',
            field=models.CharField(choices=[('not_in_house', 'Not in house'), ('in_house', 'In house'), ('checked_out', 'Checked out')], default='not_in_house', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='house_status',
            field=models.CharField(choices=[('not_in_house', 'Not in house'), ('in_house', 'In house'), ('checked_out', 'Checked out')], default='not_in_house', max_length=20),
        ),
    ]
