# Generated by Django 5.2.6 on 2025-09-12 22:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_house_status_historicalguest_house_status'),
        ('services', '0006_auto_20250913_0032'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalguestaddress',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='historicalguestaddress',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalguestemergencycontact',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='historicalguestemergencycontact',
            name='history_user',
        ),
        migrations.AlterModelOptions(
            name='guestaddress',
            options={'ordering': ['-is_primary', 'address_type']},
        ),
        migrations.RenameField(
            model_name='guestaddress',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='guestaddress',
            old_name='street',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='guest',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any allergies or dietary restrictions'),
        ),
        migrations.AddField(
            model_name='guest',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guest',
            name='marketing_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='membership_tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('vip', 'VIP')], default='bronze', max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='preferred_services',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_guests', to='services.service'),
        ),
        migrations.AddField(
            model_name='guest',
            name='sms_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Any special requirements or notes'),
        ),
        migrations.AddField(
            model_name='guest',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='guest',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guestaddress',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('billing', 'Billing')], default='home', max_length=20),
        ),
        migrations.AddField(
            model_name='guestaddress',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guestaddress',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any allergies or dietary restrictions'),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='marketing_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='membership_tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('vip', 'VIP')], default='bronze', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='sms_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Any special requirements or notes'),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guestaddress',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='guests.guest')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GuestCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('in_person', 'In Person')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('response_received', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='guests.guest')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='guests.guest')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_preferences', to='services.service')),
            ],
            options={
                'ordering': ['-rating', 'service__name'],
                'unique_together': {('guest', 'service')},
            },
        ),
        migrations.DeleteModel(
            name='GuestEmergencyContact',
        ),
        migrations.DeleteModel(
            name='HistoricalGuestAddress',
        ),
        migrations.DeleteModel(
            name='HistoricalGuestEmergencyContact',
        ),
    ]
