# Generated by Django 5.2.6 on 2025-09-12 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_remove_historicalguestaddress_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcommunication',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_communications', to='guests.guest'),
        ),
    ]
