# Generated by Django 5.2.6 on 2025-09-15 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('guests', '0004_alter_guestcommunication_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='membership_tier',
            field=models.ForeignKey(blank=True, help_text="Guest's membership tier from configuration", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='config.membershiptier'),
        ),
        migrations.AlterField(
            model_name='historicalguest',
            name='membership_tier',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Guest's membership tier from configuration", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='config.membershiptier'),
        ),
    ]
