# Generated by Django 5.2.6 on 2025-09-15 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('guests', '0005_alter_guest_membership_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='membership_tier',
            field=models.ForeignKey(blank=True, db_column='membership_tier', help_text="Guest's membership tier (references MembershipTier.name)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests_by_name', to='config.membershiptier', to_field='name'),
        ),
        migrations.AlterField(
            model_name='historicalguest',
            name='membership_tier',
            field=models.ForeignKey(blank=True, db_column='membership_tier', db_constraint=False, help_text="Guest's membership tier (references MembershipTier.name)", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='config.membershiptier', to_field='name'),
        ),
    ]
