# Generated by Django 5.2.6 on 2025-10-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0009_drop_not_null_membership_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalguest',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
